services:
  db:
    image: mysql:8.0
    container_name: blog_db
    volumes:
      - datadir:/var/lib/mysql
    environment:
      MYSQL_DATABASE: my_blog
      MYSQL_ROOT_PASSWORD: localhost1234
    ports:
      - "3306:3306"

volumes:
  datadir:
